version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-reminder-bot
    restart: unless-stopped
    volumes:
      - bot_data:/app/data
      - ./backups:/app/backups
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data: